stages:
  - build
  - test
  - style

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule"

variables:
  GIT_DEPTH: 0
  CACHIX_NAME: nixturris

.nix:
  image: registry.gitlab.com/cynerd/gitlab-ci-nix
  tags:
    - docker
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  cache:
    key: "nix"
    paths:
      - ".nix-cache"
  before_script:
    - gitlab-ci-nix-cache-before
  after_script:
    - gitlab-ci-nix-cache-after

## Build stage #################################################################
.build:
  stage: build
  extends: .nix
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "schedule"
      allow_failure: true
  script:
    - echo 'auto-allocate-uids = false' >> /etc/nix/nix.conf
    - "[ \"$CI_PIPELINE_SOURCE\" != 'schedule' ] || nix flake update"
    - nix build --log-lines 1000 .#$ARG
    - cp result/tarball/* .

build:tarballMox:
  extends: .build
  variables:
    ARG: tarballMox
  artifacts:
    expose_as: 'Installation Tarball Mox'
    paths:
      - nixos-system-aarch64-linux.tar.xz


build:tarballOmnia:
  extends: .build
  variables:
    ARG: tarballOmnia
  artifacts:
    expose_as: 'Installation Tarball Omnia'
    paths:
      - nixos-system-armv7l-linux.tar.xz

# TODO build in libvirtd or something to test also native build

## Test stage ##################################################################
.test:
  stage: test
  extends: .nix
  needs: []

nix-check:
  stage: test
  extends: .test
  script:
    - nix flake check

statix:
  stage: test
  extends: .test
  script:
    - nix run .#statix -- check .

## Style stage #################################################################
.style:
  stage: style
  extends: .nix
  needs: []
  allow_failure: true

nixfmt:
  extends: .style
  script:
    - nix fmt
    - git diff --exit-code

deadnix:
  extends: .style
  script:
    - nix run .#deadnix -- -f .

gitlint:
  extends: .style
  script:
    - git fetch
    - nix run --quiet .#gitlint -- --commits origin/master..$CI_COMMIT_SHA
