= Things to be done

NixTurris is open-source project without any monetary backing. It is just an
attempt to get NixOS and its advantages to the Turris routers. Please poke to
these topics if you have some free time.

These are big tasks. For the smaller ones please use Gitlab issues.

We should add Turris to https://nixos.wiki/wiki/NixOS_on_ARM.


== Bugs to be solved

Latest kernel doesn't work:: Only stable kernel seems to correctly work right
now. Quick test showed that latest Linux kernel crashes on PCI initialization.

Mox with module G:: Kernel is unstable when Turris Mox is used with G module
(Super Extension) and two Wi-Fi cards. This might be tied to used cards or even
to the module itself. The result is that this setup is known to be problematic.

Native build for Turris Omnia doesn't work:: There are multiple packages that
fail to build when compiled natively on armv7. This can be either due to Qemu or
more likely that they are just not prepared to be build on armv7. The most of
the packages fail their test phases as they most likely expect 64bit system.


== Improvements to be tackled

Native build in CI:: It would be good if we would check not only cross
compilation but also native build but for that we need Gitlab Runner on aarch64
and armv7l. We could probably spawn virtual machine using Qemu.

Minimal system build:: The Nix evaluation consumes considerable amount of RAM
and thus it is not possible to rebuild NixOS on the device itself without using
SWAP. The option is to cut out all modules that are just not required as they
deal with graphics output and desktop. The initial work on that is already
started in this repository but issue is that even core modules depend on desktop
specific ones.

Boot modes on Omnia to select previous profiles:: By modifying the U-Boot
environment for rescue we might be able to use Omnia standard LEDs rescue mode
selection to select older profiles. The selected led is passed just by set
environment variable to the U-Boot script but we would have to patch the U-Boot
to change the rescue environment.
